### ISSUE TITLE
Alarm the user when Xopt UCB w/ constraints UserWarning raises

### ISSUE THREAD

**Issue by wenatuhs** [xopt-org/Badger#32]
In Xopt when UCB is used with constraints in VOCS a UserWarning would raise saying that it might cause faulty behavior. In this case Badger should notify the user that it's better to try EI w/ constraints. But we need to do it in a smart way that does not annoy the user with too many alarms since this warning will be triggered anytime a UCB w/ constraints routine is loaded (say, refreshing the routine list and the latest run one is such a routine).

**Comment by roussel-ryan** [comment]
Removed UCB from list of routines, might be added back in later
